version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.11.1
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_test_results:
          path: ~/mochawesome-report
      - store_artifacts:
          path: mochawesome-report
